name: VSCode language Yesod CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10','12','14']

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install yq
      run: sudo snap install yq

    - name: Get the external tmLanguage
      run: bash ./test/resources/getExternalTmLanguage.sh

    - name: Test syntax highlighting
      run: npm run test
